### PR TITLE
Support animated terrain via tile properties

### PR DESCRIPTION
**Pull request by noahgibbs**
This is on top of the RSpec 3 pull request, though I suppose you could cherry-pick the top commit easily enough.

### CODE REVIEW

**Comment by shawn42** [comment]
:+1: Have you looked at how the JSON parser handles tile properties (or doesn't)

**Comment by noahgibbs** [comment]
I haven't. I've been mining interesting XML maps and tilesets from TheManaProject-related stuff, but they don't use JSON. So I have good test data for XML, but none for JSON.

**Comment by burtlo** [comment]
Unrelated: thanks for the love and attention towards the project.

**Comment by burtlo** [comment]
Makes it awesome so that when the next Ludum Dare rolls around I can find delightful new features.

**Pull request merged**
