### PR TITLE
Add TMX JSON exporter to Tmx::Map object with simple re-export test

### PR DESCRIPTION
**Pull request by noahgibbs**

### CODE REVIEW

**Comment by noahgibbs** [comment]
I'm doing this for my own project. You could use it to write a really simple command-line JSON exporter. I'm doing something like that but with Rack middleware to serve XML-flavored TMX files as though they had been pre-exported to JSON, but without the manual export step.

This doesn't do anything fancy relative to TSX files. So it works better with embedded tilesets, just like regular JSON exports from Tiled.

**Comment by shawn42** [comment]
Oh neat, I hadn't really thought of that use case!  Thanks for the contribution. Do you have a link to your project that I can look at?

**Comment by noahgibbs** [comment]
The one that works is here: "https://github.com/noahgibbs/trackless_sea". It's kind of a pain to set up, so here's a link to what it looks like when it's running: https://www.dropbox.com/s/f49hgt4pc4y1kj9/trackless_testing.gif?dl=0

(It's an animated gif, so view with something that can see those.)

I'm putting together something less awful to get configured, but it's not done yet.

**Comment by shawn42** [comment]
Cool! I'll have to check it out when I'm not working.  ;)

**Pull request merged**
